alias nr='re nginx'
alias pr='re php54-fpm'
alias nf='cd /opt/local/etc/nginx'
alias pf='cd /opt/local/etc/php54'
alias sj='ssh root@zhangshenjia.com'
alias pe='pledit'
alias me='/Applications/Mou.app/Contents/MacOS/Mou'
alias s='cd /Users/zhangshenjia'
