alias php='/usr/local/opt/php@7.0/bin/php'
alias nr='sudo nginx -s reload'
alias pr='re php54-fpm'
alias cpd='/Users/zhangshenjia/Documents/software/web/php/phpcpd.phar'
alias te='e /Users/zhangshenjia/test/test.php'
alias tt='php /Users/zhangshenjia/test/test.php'
